"""Seed data for the multi-category TechShop catalog."""

from __future__ import annotations

from uuid import NAMESPACE_URL, uuid5


SEED_NAMESPACE = uuid5(NAMESPACE_URL, "techshop.catalog.seed")


def stable_uuid(kind: str, value: str) -> str:
    """Return a deterministic UUID for seed entities."""
    return str(uuid5(SEED_NAMESPACE, f"{kind}:{value}"))


def image(seed: str) -> str:
    return f"https://picsum.photos/seed/{seed}/960/640"


CATEGORY_SEED_DATA = [
    {
        "id": stable_uuid("category", "electronics"),
        "slug": "electronics",
        "name": "Electronics",
        "description": "Laptop, mobile, tablet, audio gear and digital lifestyle devices.",
        "image_url": image("electronics"),
        "sort_order": 10,
    },
    {
        "id": stable_uuid("category", "fashion"),
        "slug": "fashion",
        "name": "Fashion",
        "description": "Daily-wear tops, bottoms, shoes, sandals, hats and wardrobe essentials.",
        "image_url": image("fashion"),
        "sort_order": 20,
    },
    {
        "id": stable_uuid("category", "cosmetics"),
        "slug": "cosmetics",
        "name": "Cosmetics",
        "description": "Lipsticks, foundation, sunscreen and skincare-ready beauty products.",
        "image_url": image("cosmetics"),
        "sort_order": 30,
    },
    {
        "id": stable_uuid("category", "home_appliances"),
        "slug": "home_appliances",
        "name": "Home Appliances",
        "description": "Air conditioners, refrigerators, rice cookers and smart home appliances.",
        "image_url": image("home-appliances"),
        "sort_order": 40,
    },
    {
        "id": stable_uuid("category", "accessories"),
        "slug": "accessories",
        "name": "Accessories",
        "description": "Backpacks, eyewear, belts, phone cases and wearable accessories.",
        "image_url": image("accessories"),
        "sort_order": 50,
    },
    {
        "id": stable_uuid("category", "books"),
        "slug": "books",
        "name": "Books",
        "description": "Business, design, self-growth and technology books for modern learners.",
        "image_url": image("books"),
        "sort_order": 60,
    },
    {
        "id": stable_uuid("category", "groceries"),
        "slug": "groceries",
        "name": "Groceries",
        "description": "Healthy snacks, coffee and pantry picks for home and office.",
        "image_url": image("groceries"),
        "sort_order": 70,
    },
    {
        "id": stable_uuid("category", "sports"),
        "slug": "sports",
        "name": "Sports",
        "description": "Yoga, running, training and camping essentials for active lifestyles.",
        "image_url": image("sports"),
        "sort_order": 80,
    },
    {
        "id": stable_uuid("category", "baby_kids"),
        "slug": "baby_kids",
        "name": "Baby & Kids",
        "description": "Baby care and family essentials for young households.",
        "image_url": image("baby-kids"),
        "sort_order": 90,
    },
    {
        "id": stable_uuid("category", "furniture"),
        "slug": "furniture",
        "name": "Furniture",
        "description": "Compact living and work furniture for home setups.",
        "image_url": image("furniture"),
        "sort_order": 100,
    },
    {
        "id": stable_uuid("category", "office"),
        "slug": "office",
        "name": "Office",
        "description": "Desk tools, planners and work-friendly supplies.",
        "image_url": image("office"),
        "sort_order": 110,
    },
    {
        "id": stable_uuid("category", "toys"),
        "slug": "toys",
        "name": "Toys",
        "description": "Board games and educational play kits for family time.",
        "image_url": image("toys"),
        "sort_order": 120,
    },
]


BRAND_SEED_DATA = [
    {"id": stable_uuid("brand", "nova-tech"), "slug": "nova-tech", "name": "Nova Tech"},
    {"id": stable_uuid("brand", "aurora-mobile"), "slug": "aurora-mobile", "name": "Aurora Mobile"},
    {"id": stable_uuid("brand", "polar-home"), "slug": "polar-home", "name": "Polar Home"},
    {"id": stable_uuid("brand", "urban-vogue"), "slug": "urban-vogue", "name": "Urban Vogue"},
    {"id": stable_uuid("brand", "velvet-glow"), "slug": "velvet-glow", "name": "Velvet Glow"},
    {"id": stable_uuid("brand", "trailblaze"), "slug": "trailblaze", "name": "TrailBlaze"},
    {"id": stable_uuid("brand", "carry-all"), "slug": "carry-all", "name": "Carry All"},
    {"id": stable_uuid("brand", "mindforge"), "slug": "mindforge", "name": "MindForge Press"},
    {"id": stable_uuid("brand", "green-basket"), "slug": "green-basket", "name": "Green Basket"},
    {"id": stable_uuid("brand", "tinybloom"), "slug": "tinybloom", "name": "TinyBloom"},
    {"id": stable_uuid("brand", "north-haven"), "slug": "north-haven", "name": "North Haven"},
    {"id": stable_uuid("brand", "playcraft"), "slug": "playcraft", "name": "PlayCraft"},
]


PRODUCT_TYPE_SEED_DATA = [
    {"id": stable_uuid("product_type", "LAPTOP"), "code": "LAPTOP", "name": "Laptop"},
    {"id": stable_uuid("product_type", "MOBILE"), "code": "MOBILE", "name": "Mobile"},
    {"id": stable_uuid("product_type", "TABLET"), "code": "TABLET", "name": "Tablet"},
    {"id": stable_uuid("product_type", "AUDIO"), "code": "AUDIO", "name": "Audio Device"},
    {"id": stable_uuid("product_type", "AIR_CONDITIONER"), "code": "AIR_CONDITIONER", "name": "Air Conditioner"},
    {"id": stable_uuid("product_type", "REFRIGERATOR"), "code": "REFRIGERATOR", "name": "Refrigerator"},
    {"id": stable_uuid("product_type", "HOME_DEVICE"), "code": "HOME_DEVICE", "name": "Home Device"},
    {"id": stable_uuid("product_type", "TOP"), "code": "TOP", "name": "Top"},
    {"id": stable_uuid("product_type", "BOTTOM"), "code": "BOTTOM", "name": "Bottom"},
    {"id": stable_uuid("product_type", "SHOES"), "code": "SHOES", "name": "Shoes"},
    {"id": stable_uuid("product_type", "SANDALS"), "code": "SANDALS", "name": "Sandals"},
    {"id": stable_uuid("product_type", "HAT"), "code": "HAT", "name": "Hat"},
    {"id": stable_uuid("product_type", "LIPSTICK"), "code": "LIPSTICK", "name": "Lipstick"},
    {"id": stable_uuid("product_type", "FOUNDATION"), "code": "FOUNDATION", "name": "Foundation"},
    {"id": stable_uuid("product_type", "SUNSCREEN"), "code": "SUNSCREEN", "name": "Sunscreen"},
    {"id": stable_uuid("product_type", "SKINCARE"), "code": "SKINCARE", "name": "Skincare"},
    {"id": stable_uuid("product_type", "ACCESSORY"), "code": "ACCESSORY", "name": "Accessory"},
    {"id": stable_uuid("product_type", "BOOK"), "code": "BOOK", "name": "Book"},
    {"id": stable_uuid("product_type", "GROCERY"), "code": "GROCERY", "name": "Grocery"},
    {"id": stable_uuid("product_type", "SPORTS_GEAR"), "code": "SPORTS_GEAR", "name": "Sports Gear"},
    {"id": stable_uuid("product_type", "BABY_CARE"), "code": "BABY_CARE", "name": "Baby Care"},
    {"id": stable_uuid("product_type", "FURNITURE"), "code": "FURNITURE", "name": "Furniture"},
    {"id": stable_uuid("product_type", "STATIONERY"), "code": "STATIONERY", "name": "Stationery"},
    {"id": stable_uuid("product_type", "TOY"), "code": "TOY", "name": "Toy"},
]


PRODUCT_SEED_DATA = [
    {
        "slug": "laptop-aero-14",
        "name": "Laptop Aero 14",
        "category_slug": "electronics",
        "brand_slug": "nova-tech",
        "product_type_code": "LAPTOP",
        "price": "28990000",
        "featured": True,
        "rating": 4.8,
        "stock": 18,
        "tags": ["laptop", "ultrabook", "office"],
        "item_type": "laptop",
    },
    {
        "slug": "laptop-studio-pro-16",
        "name": "Laptop Studio Pro 16",
        "category_slug": "electronics",
        "brand_slug": "nova-tech",
        "product_type_code": "LAPTOP",
        "price": "35990000",
        "featured": True,
        "rating": 4.9,
        "stock": 12,
        "tags": ["laptop", "creator", "performance"],
        "item_type": "laptop",
    },
    {
        "slug": "mobile-aurora-x5",
        "name": "Mobile Aurora X5",
        "category_slug": "electronics",
        "brand_slug": "aurora-mobile",
        "product_type_code": "MOBILE",
        "price": "12990000",
        "featured": True,
        "rating": 4.7,
        "stock": 28,
        "tags": ["mobile", "5g", "camera"],
        "item_type": "mobile",
    },
    {
        "slug": "mobile-aurora-lite-5g",
        "name": "Mobile Aurora Lite 5G",
        "category_slug": "electronics",
        "brand_slug": "aurora-mobile",
        "product_type_code": "MOBILE",
        "price": "7990000",
        "featured": False,
        "rating": 4.5,
        "stock": 35,
        "tags": ["mobile", "budget", "5g"],
        "item_type": "mobile",
    },
    {
        "slug": "tablet-flex-tab-11",
        "name": "Tablet Flex Tab 11",
        "category_slug": "electronics",
        "brand_slug": "nova-tech",
        "product_type_code": "TABLET",
        "price": "10990000",
        "featured": False,
        "rating": 4.6,
        "stock": 20,
        "tags": ["tablet", "study", "entertainment"],
        "item_type": "tablet",
    },
    {
        "slug": "headphones-wavebuds-pro",
        "name": "Headphones WaveBuds Pro",
        "category_slug": "electronics",
        "brand_slug": "nova-tech",
        "product_type_code": "AUDIO",
        "price": "2490000",
        "featured": False,
        "rating": 4.4,
        "stock": 40,
        "tags": ["audio", "wireless", "noise-cancelling"],
        "item_type": "headphones",
    },
    {
        "slug": "smartwatch-pulse-s2",
        "name": "Smartwatch Pulse S2",
        "category_slug": "electronics",
        "brand_slug": "aurora-mobile",
        "product_type_code": "ACCESSORY",
        "price": "3190000",
        "featured": False,
        "rating": 4.3,
        "stock": 22,
        "tags": ["smartwatch", "fitness", "wearable"],
        "item_type": "smartwatch",
    },
    {
        "slug": "air-conditioner-coolbreeze-inverter",
        "name": "Air Conditioner CoolBreeze Inverter",
        "category_slug": "home_appliances",
        "brand_slug": "polar-home",
        "product_type_code": "AIR_CONDITIONER",
        "price": "13490000",
        "featured": True,
        "rating": 4.7,
        "stock": 11,
        "tags": ["air-conditioner", "inverter", "cooling"],
        "item_type": "air_conditioner",
    },
    {
        "slug": "refrigerator-frostmax-360l",
        "name": "Refrigerator FrostMax 360L",
        "category_slug": "home_appliances",
        "brand_slug": "polar-home",
        "product_type_code": "REFRIGERATOR",
        "price": "15990000",
        "featured": True,
        "rating": 4.8,
        "stock": 9,
        "tags": ["refrigerator", "family", "inverter"],
        "item_type": "refrigerator",
    },
    {
        "slug": "washing-machine-cleanwave-10kg",
        "name": "Washing Machine CleanWave 10kg",
        "category_slug": "home_appliances",
        "brand_slug": "polar-home",
        "product_type_code": "HOME_DEVICE",
        "price": "9990000",
        "featured": False,
        "rating": 4.5,
        "stock": 14,
        "tags": ["washing-machine", "laundry", "home"],
        "item_type": "washing_machine",
    },
    {
        "slug": "vacuum-robot-cleansphere-mini",
        "name": "Vacuum Robot CleanSphere Mini",
        "category_slug": "home_appliances",
        "brand_slug": "polar-home",
        "product_type_code": "HOME_DEVICE",
        "price": "5490000",
        "featured": False,
        "rating": 4.4,
        "stock": 17,
        "tags": ["robot-vacuum", "smart-home", "cleaning"],
        "item_type": "vacuum",
    },
    {
        "slug": "rice-cooker-smartpot-18l",
        "name": "Rice Cooker SmartPot 1.8L",
        "category_slug": "home_appliances",
        "brand_slug": "polar-home",
        "product_type_code": "HOME_DEVICE",
        "price": "1490000",
        "featured": False,
        "rating": 4.2,
        "stock": 33,
        "tags": ["rice-cooker", "kitchen", "daily"],
        "item_type": "rice_cooker",
    },
    {
        "slug": "air-purifier-breezeguard-300",
        "name": "Air Purifier BreezeGuard 300",
        "category_slug": "home_appliances",
        "brand_slug": "polar-home",
        "product_type_code": "HOME_DEVICE",
        "price": "6290000",
        "featured": False,
        "rating": 4.6,
        "stock": 15,
        "tags": ["air-purifier", "home", "wellness"],
        "item_type": "air_purifier",
    },
    {
        "slug": "ao-thun-essential-cotton",
        "name": "Ao thun Essential Cotton",
        "category_slug": "fashion",
        "brand_slug": "urban-vogue",
        "product_type_code": "TOP",
        "price": "249000",
        "featured": False,
        "rating": 4.4,
        "stock": 60,
        "tags": ["ao", "tshirt", "cotton"],
        "item_type": "ao",
    },
    {
        "slug": "ao-khoac-urban-shell",
        "name": "Ao khoac Urban Shell",
        "category_slug": "fashion",
        "brand_slug": "urban-vogue",
        "product_type_code": "TOP",
        "price": "799000",
        "featured": True,
        "rating": 4.6,
        "stock": 26,
        "tags": ["ao", "jacket", "streetwear"],
        "item_type": "ao",
    },
    {
        "slug": "quan-jean-straight-fit",
        "name": "Quan jean Straight Fit",
        "category_slug": "fashion",
        "brand_slug": "urban-vogue",
        "product_type_code": "BOTTOM",
        "price": "649000",
        "featured": False,
        "rating": 4.5,
        "stock": 42,
        "tags": ["quan", "jean", "daily"],
        "item_type": "quan",
    },
    {
        "slug": "quan-jogger-move-easy",
        "name": "Quan jogger Move Easy",
        "category_slug": "fashion",
        "brand_slug": "urban-vogue",
        "product_type_code": "BOTTOM",
        "price": "459000",
        "featured": False,
        "rating": 4.3,
        "stock": 38,
        "tags": ["quan", "jogger", "comfort"],
        "item_type": "quan",
    },
    {
        "slug": "giay-sneaker-cloud-runner",
        "name": "Giay sneaker Cloud Runner",
        "category_slug": "fashion",
        "brand_slug": "urban-vogue",
        "product_type_code": "SHOES",
        "price": "1199000",
        "featured": True,
        "rating": 4.7,
        "stock": 24,
        "tags": ["giay", "sneaker", "lifestyle"],
        "item_type": "giay",
    },
    {
        "slug": "dep-sandal-coastline",
        "name": "Dep sandal Coastline",
        "category_slug": "fashion",
        "brand_slug": "urban-vogue",
        "product_type_code": "SANDALS",
        "price": "359000",
        "featured": False,
        "rating": 4.2,
        "stock": 45,
        "tags": ["dep", "sandal", "summer"],
        "item_type": "dep",
    },
    {
        "slug": "mu-bucket-weekend",
        "name": "Mu bucket Weekend",
        "category_slug": "fashion",
        "brand_slug": "urban-vogue",
        "product_type_code": "HAT",
        "price": "199000",
        "featured": False,
        "rating": 4.1,
        "stock": 52,
        "tags": ["mu", "bucket", "accessory"],
        "item_type": "mu",
    },
    {
        "slug": "dam-midi-softline",
        "name": "Dam midi SoftLine",
        "category_slug": "fashion",
        "brand_slug": "urban-vogue",
        "product_type_code": "TOP",
        "price": "899000",
        "featured": False,
        "rating": 4.5,
        "stock": 19,
        "tags": ["dress", "women", "office"],
        "item_type": "dam",
    },
    {
        "slug": "son-lip-velvet-maple",
        "name": "Son Lip Velvet Maple",
        "category_slug": "cosmetics",
        "brand_slug": "velvet-glow",
        "product_type_code": "LIPSTICK",
        "price": "289000",
        "featured": True,
        "rating": 4.8,
        "stock": 70,
        "tags": ["son", "lipstick", "makeup"],
        "item_type": "son",
    },
    {
        "slug": "son-lip-dewy-rose",
        "name": "Son Lip Dewy Rose",
        "category_slug": "cosmetics",
        "brand_slug": "velvet-glow",
        "product_type_code": "LIPSTICK",
        "price": "259000",
        "featured": False,
        "rating": 4.6,
        "stock": 64,
        "tags": ["son", "gloss", "makeup"],
        "item_type": "son",
    },
    {
        "slug": "kem-nen-second-skin",
        "name": "Kem nen Second Skin",
        "category_slug": "cosmetics",
        "brand_slug": "velvet-glow",
        "product_type_code": "FOUNDATION",
        "price": "429000",
        "featured": True,
        "rating": 4.7,
        "stock": 34,
        "tags": ["kem-nen", "foundation", "base"],
        "item_type": "kem_nen",
    },
    {
        "slug": "kem-nen-airfit-cushion",
        "name": "Kem nen AirFit Cushion",
        "category_slug": "cosmetics",
        "brand_slug": "velvet-glow",
        "product_type_code": "FOUNDATION",
        "price": "469000",
        "featured": False,
        "rating": 4.5,
        "stock": 29,
        "tags": ["cushion", "kem-nen", "glow"],
        "item_type": "kem_nen",
    },
    {
        "slug": "kem-chong-nang-daily-shield-spf50",
        "name": "Kem chong nang Daily Shield SPF50",
        "category_slug": "cosmetics",
        "brand_slug": "velvet-glow",
        "product_type_code": "SUNSCREEN",
        "price": "349000",
        "featured": True,
        "rating": 4.9,
        "stock": 56,
        "tags": ["kem-chong-nang", "spf50", "uv"],
        "item_type": "kem_chong_nang",
    },
    {
        "slug": "sua-rua-mat-foam-balance",
        "name": "Sua rua mat Foam Balance",
        "category_slug": "cosmetics",
        "brand_slug": "velvet-glow",
        "product_type_code": "SKINCARE",
        "price": "219000",
        "featured": False,
        "rating": 4.4,
        "stock": 41,
        "tags": ["cleanser", "skincare", "foam"],
        "item_type": "sua_rua_mat",
    },
    {
        "slug": "serum-niacinamide-10",
        "name": "Serum Niacinamide 10%",
        "category_slug": "cosmetics",
        "brand_slug": "velvet-glow",
        "product_type_code": "SKINCARE",
        "price": "389000",
        "featured": False,
        "rating": 4.6,
        "stock": 37,
        "tags": ["serum", "skincare", "brightening"],
        "item_type": "serum",
    },
    {
        "slug": "balo-commute-flex",
        "name": "Balo Commute Flex",
        "category_slug": "accessories",
        "brand_slug": "carry-all",
        "product_type_code": "ACCESSORY",
        "price": "899000",
        "featured": True,
        "rating": 4.7,
        "stock": 25,
        "tags": ["balo", "backpack", "travel"],
        "item_type": "balo",
    },
    {
        "slug": "op-lung-magsafe-clear",
        "name": "Op lung MagSafe Clear",
        "category_slug": "accessories",
        "brand_slug": "carry-all",
        "product_type_code": "ACCESSORY",
        "price": "249000",
        "featured": False,
        "rating": 4.3,
        "stock": 58,
        "tags": ["phone-case", "accessory", "magsafe"],
        "item_type": "op_lung",
    },
    {
        "slug": "kinh-mat-sunframe",
        "name": "Kinh mat SunFrame",
        "category_slug": "accessories",
        "brand_slug": "carry-all",
        "product_type_code": "ACCESSORY",
        "price": "559000",
        "featured": False,
        "rating": 4.4,
        "stock": 31,
        "tags": ["kinh", "eyewear", "summer"],
        "item_type": "kinh",
    },
    {
        "slug": "that-lung-leather-line",
        "name": "That lung Leather Line",
        "category_slug": "accessories",
        "brand_slug": "carry-all",
        "product_type_code": "ACCESSORY",
        "price": "399000",
        "featured": False,
        "rating": 4.2,
        "stock": 44,
        "tags": ["belt", "leather", "men"],
        "item_type": "that_lung",
    },
    {
        "slug": "book-deep-work-playbook",
        "name": "Book Deep Work Playbook",
        "category_slug": "books",
        "brand_slug": "mindforge",
        "product_type_code": "BOOK",
        "price": "179000",
        "featured": False,
        "rating": 4.8,
        "stock": 67,
        "tags": ["book", "productivity", "focus"],
        "item_type": "book",
    },
    {
        "slug": "book-ml-for-builders",
        "name": "Book ML for Builders",
        "category_slug": "books",
        "brand_slug": "mindforge",
        "product_type_code": "BOOK",
        "price": "249000",
        "featured": True,
        "rating": 4.9,
        "stock": 36,
        "tags": ["book", "machine-learning", "engineering"],
        "item_type": "book",
    },
    {
        "slug": "book-brand-design-systems",
        "name": "Book Brand Design Systems",
        "category_slug": "books",
        "brand_slug": "mindforge",
        "product_type_code": "BOOK",
        "price": "219000",
        "featured": False,
        "rating": 4.5,
        "stock": 29,
        "tags": ["book", "design", "branding"],
        "item_type": "book",
    },
    {
        "slug": "book-lean-business-notes",
        "name": "Book Lean Business Notes",
        "category_slug": "books",
        "brand_slug": "mindforge",
        "product_type_code": "BOOK",
        "price": "199000",
        "featured": False,
        "rating": 4.4,
        "stock": 33,
        "tags": ["book", "business", "strategy"],
        "item_type": "book",
    },
    {
        "slug": "granola-honey-almond",
        "name": "Granola Honey Almond",
        "category_slug": "groceries",
        "brand_slug": "green-basket",
        "product_type_code": "GROCERY",
        "price": "165000",
        "featured": False,
        "rating": 4.6,
        "stock": 73,
        "tags": ["granola", "healthy", "breakfast"],
        "item_type": "granola",
    },
    {
        "slug": "coffee-single-origin-dalat",
        "name": "Coffee Single Origin Da Lat",
        "category_slug": "groceries",
        "brand_slug": "green-basket",
        "product_type_code": "GROCERY",
        "price": "189000",
        "featured": True,
        "rating": 4.8,
        "stock": 48,
        "tags": ["coffee", "beans", "dalat"],
        "item_type": "coffee",
    },
    {
        "slug": "nuts-premium-mix-500g",
        "name": "Nuts Premium Mix 500g",
        "category_slug": "groceries",
        "brand_slug": "green-basket",
        "product_type_code": "GROCERY",
        "price": "175000",
        "featured": False,
        "rating": 4.7,
        "stock": 62,
        "tags": ["nuts", "healthy", "snack"],
        "item_type": "nuts",
    },
    {
        "slug": "matcha-latte-starter-kit",
        "name": "Matcha Latte Starter Kit",
        "category_slug": "groceries",
        "brand_slug": "green-basket",
        "product_type_code": "GROCERY",
        "price": "229000",
        "featured": False,
        "rating": 4.3,
        "stock": 27,
        "tags": ["matcha", "drink", "starter-kit"],
        "item_type": "matcha",
    },
    {
        "slug": "tham-yoga-align-mat",
        "name": "Tham yoga Align Mat",
        "category_slug": "sports",
        "brand_slug": "trailblaze",
        "product_type_code": "SPORTS_GEAR",
        "price": "699000",
        "featured": False,
        "rating": 4.6,
        "stock": 39,
        "tags": ["yoga", "fitness", "mat"],
        "item_type": "tham_yoga",
    },
    {
        "slug": "ta-tay-hex-10kg-pair",
        "name": "Ta tay Hex 10kg Pair",
        "category_slug": "sports",
        "brand_slug": "trailblaze",
        "product_type_code": "SPORTS_GEAR",
        "price": "1299000",
        "featured": False,
        "rating": 4.5,
        "stock": 21,
        "tags": ["dumbbell", "strength", "home-gym"],
        "item_type": "ta_tay",
    },
    {
        "slug": "giay-running-skyline-2",
        "name": "Giay running Skyline 2",
        "category_slug": "sports",
        "brand_slug": "trailblaze",
        "product_type_code": "SHOES",
        "price": "1599000",
        "featured": True,
        "rating": 4.7,
        "stock": 23,
        "tags": ["giay", "running", "sport"],
        "item_type": "giay",
    },
    {
        "slug": "leu-cam-trai-weekender-4p",
        "name": "Leu cam trai Weekender 4P",
        "category_slug": "sports",
        "brand_slug": "trailblaze",
        "product_type_code": "SPORTS_GEAR",
        "price": "2399000",
        "featured": True,
        "rating": 4.8,
        "stock": 16,
        "tags": ["camping", "tent", "outdoor"],
        "item_type": "leu",
    },
    {
        "slug": "binh-nuoc-trail-steel-1l",
        "name": "Binh nuoc Trail Steel 1L",
        "category_slug": "sports",
        "brand_slug": "trailblaze",
        "product_type_code": "SPORTS_GEAR",
        "price": "329000",
        "featured": False,
        "rating": 4.4,
        "stock": 47,
        "tags": ["water-bottle", "hiking", "outdoor"],
        "item_type": "binh_nuoc",
    },
]
