# Generated by Django 5.2.13 on 2026-04-11 11:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Warehouse code', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Warehouse name', max_length=200)),
                ('warehouse_type', models.CharField(choices=[('main', 'main'), ('branch', 'branch'), ('third_party', 'third_party'), ('holding', 'holding')], default='main', help_text='Type of warehouse', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Physical location/address', max_length=255, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'db_table': 'warehouses',
            },
        ),
        migrations.CreateModel(
            name='StockItemModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField(db_index=True, help_text='UUID of product from product_service')),
                ('variant_id', models.UUIDField(blank=True, db_index=True, help_text='UUID of product variant (nullable if product has no variants)', null=True)),
                ('sku', models.CharField(blank=True, help_text='SKU from product_service', max_length=100, null=True)),
                ('warehouse_code', models.CharField(db_index=True, default='MAIN', help_text='Warehouse or location code', max_length=50)),
                ('on_hand_quantity', models.BigIntegerField(default=0, help_text='Actual stock on hand', validators=[django.core.validators.MinValueValidator(0)])),
                ('reserved_quantity', models.BigIntegerField(default=0, help_text='Total quantity in active reservations', validators=[django.core.validators.MinValueValidator(0)])),
                ('safety_stock', models.BigIntegerField(default=0, help_text='Minimum stock level for alerts', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this stock item is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock Item',
                'verbose_name_plural': 'Stock Items',
                'db_table': 'stock_items',
                'indexes': [models.Index(fields=['product_id', 'warehouse_code'], name='stock_items_product_53fa78_idx'), models.Index(fields=['variant_id', 'warehouse_code'], name='stock_items_variant_6e04d2_idx'), models.Index(fields=['is_active', 'on_hand_quantity'], name='stock_items_is_acti_cfd190_idx'), models.Index(fields=['updated_at'], name='stock_items_updated_041199_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('product_id', 'variant_id', 'warehouse_code'), name='unique_stock_per_warehouse'), models.CheckConstraint(condition=models.Q(('on_hand_quantity__gte', 0)), name='on_hand_non_negative'), models.CheckConstraint(condition=models.Q(('reserved_quantity__gte', 0)), name='reserved_non_negative'), models.CheckConstraint(condition=models.Q(('reserved_quantity__lte', models.F('on_hand_quantity'))), name='reserved_not_exceeds_onhand')],
            },
        ),
        migrations.CreateModel(
            name='StockMovementModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField(db_index=True)),
                ('variant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('movement_type', models.CharField(choices=[('stock_in', 'stock_in'), ('stock_out', 'stock_out'), ('reservation_created', 'reservation_created'), ('reservation_released', 'reservation_released'), ('reservation_confirmed', 'reservation_confirmed'), ('adjustment_increase', 'adjustment_increase'), ('adjustment_decrease', 'adjustment_decrease'), ('correction', 'correction')], db_index=True, help_text='Type of inventory movement', max_length=30)),
                ('quantity', models.BigIntegerField(help_text='Quantity involved in this movement', validators=[django.core.validators.MinValueValidator(1)])),
                ('reference_type', models.CharField(blank=True, help_text='Type of reference (order, purchase_order, etc.)', max_length=30, null=True)),
                ('reference_id', models.CharField(blank=True, db_index=True, help_text='ID of referenced entity (order_id, purchase_order_id, etc.)', max_length=100, null=True)),
                ('note', models.TextField(blank=True, help_text='Reason or note for this movement', null=True)),
                ('created_by', models.UUIDField(blank=True, help_text='User who created this movement', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('stock_item', models.ForeignKey(help_text='Reference to stock item', on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stockitemmodel')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'db_table': 'stock_movements',
                'get_latest_by': 'created_at',
                'indexes': [models.Index(fields=['stock_item', 'created_at'], name='stock_movem_stock_i_169345_idx'), models.Index(fields=['product_id', 'created_at'], name='stock_movem_product_9796a2_idx'), models.Index(fields=['movement_type', 'created_at'], name='stock_movem_movemen_d2f919_idx'), models.Index(fields=['reference_type', 'reference_id'], name='stock_movem_referen_a0d8b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockReservationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reservation_code', models.CharField(db_index=True, help_text='Unique code for this reservation (for idempotency)', max_length=100, unique=True)),
                ('product_id', models.UUIDField(db_index=True)),
                ('variant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('order_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('cart_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('quantity', models.BigIntegerField(help_text='Quantity reserved', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('active', 'active'), ('confirmed', 'confirmed'), ('released', 'released'), ('expired', 'expired'), ('cancelled', 'cancelled')], db_index=True, default='active', help_text='Current reservation status', max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When this reservation expires')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock_item', models.ForeignKey(help_text='Reference to stock item being reserved', on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.stockitemmodel')),
            ],
            options={
                'verbose_name': 'Stock Reservation',
                'verbose_name_plural': 'Stock Reservations',
                'db_table': 'stock_reservations',
                'indexes': [models.Index(fields=['status', 'expires_at'], name='stock_reser_status_da6fe9_idx'), models.Index(fields=['order_id', 'status'], name='stock_reser_order_i_f5f13e_idx'), models.Index(fields=['cart_id', 'status'], name='stock_reser_cart_id_c8c948_idx'), models.Index(fields=['product_id', 'status'], name='stock_reser_product_3ce15a_idx'), models.Index(fields=['user_id', 'status'], name='stock_reser_user_id_faf9ed_idx'), models.Index(fields=['created_at'], name='stock_reser_created_efcfb0_idx')],
            },
        ),
    ]
