# Generated by Django 5.2.13 on 2026-04-11 11:21

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True, help_text='UUID of user who owns this cart')),
                ('status', models.CharField(choices=[('active', 'active'), ('checked_out', 'checked_out'), ('abandoned', 'abandoned'), ('expired', 'expired'), ('merged', 'merged')], db_index=True, default='active', help_text='Current cart status', max_length=20)),
                ('currency', models.CharField(default='USD', help_text='Currency code (ISO 4217)', max_length=3)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal before tax/shipping', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_quantity', models.BigIntegerField(default=0, help_text='Total quantity of all items', validators=[django.core.validators.MinValueValidator(0)])),
                ('item_count', models.BigIntegerField(default=0, help_text='Number of unique items', validators=[django.core.validators.MinValueValidator(0)])),
                ('last_activity_at', models.DateTimeField(auto_now=True, help_text='Last time cart was modified')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When cart was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When cart was last updated')),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'status'], name='cart_cartmo_user_id_613e86_idx'), models.Index(fields=['status', 'updated_at'], name='cart_cartmo_status_197879_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user_id', 'status'), name='one_active_cart_per_user')],
            },
        ),
        migrations.CreateModel(
            name='CartItemModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField(db_index=True, help_text='UUID of product from product_service')),
                ('variant_id', models.UUIDField(blank=True, db_index=True, help_text='UUID of product variant (nullable if product has no variants)', null=True)),
                ('quantity', models.BigIntegerField(default=1, help_text='Quantity of this item in cart', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price_snapshot', models.DecimalField(decimal_places=2, help_text='Unit price at time of adding to cart', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='USD', help_text='Currency code', max_length=3)),
                ('product_name_snapshot', models.CharField(help_text='Product name at time of adding', max_length=255)),
                ('product_slug_snapshot', models.CharField(help_text='Product slug for linking', max_length=255)),
                ('variant_name_snapshot', models.CharField(blank=True, help_text='Variant name if applicable', max_length=255, null=True)),
                ('brand_name_snapshot', models.CharField(blank=True, help_text='Brand name at time of adding', max_length=255, null=True)),
                ('category_name_snapshot', models.CharField(blank=True, help_text='Category name at time of adding', max_length=255, null=True)),
                ('sku', models.CharField(blank=True, help_text='SKU from product_service', max_length=100, null=True)),
                ('thumbnail_url_snapshot', models.URLField(blank=True, help_text='Thumbnail URL at time of adding', max_length=500, null=True)),
                ('attributes_snapshot', models.JSONField(default=dict, help_text='Product attributes snapshot (JSON)')),
                ('status', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable'), ('low_stock', 'low_stock'), ('out_of_stock', 'out_of_stock'), ('product_inactive', 'product_inactive'), ('variant_not_found', 'variant_not_found')], default='available', help_text='Current item status (availability)', max_length=30)),
                ('availability_checked_at', models.DateTimeField(blank=True, help_text='When availability was last checked', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When item was added to cart')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When item was last updated')),
                ('cart', models.ForeignKey(help_text='Parent cart', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cartmodel')),
            ],
            options={
                'indexes': [models.Index(fields=['cart', 'product_id', 'variant_id'], name='cart_cartit_cart_id_c3c814_idx'), models.Index(fields=['cart', 'status'], name='cart_cartit_cart_id_e8a32e_idx')],
                'constraints': [models.UniqueConstraint(fields=('cart', 'product_id', 'variant_id'), name='unique_product_in_cart')],
            },
        ),
    ]
