# Generated by Django 5.2.13 on 2026-04-11 10:13

import modules.identity.domain.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='address',
            new_name='identity_ad_user_id_15842f_idx',
            old_name='identity_add_user_id_is_def_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='identity_us_email_bcdd3b_idx',
            old_name='identity_use_email_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='identity_us_role_d94918_idx',
            old_name='identity_use_role_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='identity_us_is_acti_b0d1b1_idx',
            old_name='identity_use_is_act_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='identity_us_created_7cdce4_idx',
            old_name='identity_use_creat_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'CUSTOMER'), ('staff', 'STAFF'), ('admin', 'ADMIN')], db_index=True, default=modules.identity.domain.enums.UserRole['CUSTOMER'], max_length=20),
        ),
    ]
